[package]
name = "terraform-bindgen"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"codegen",
	"schema"
]
exclude = [
	"examples/kubernetes"
]

[dependencies]
anyhow = "1.0.69"
heck = "0.4.1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
toml = "0.7.2"
terraform-bindgen-codegen = { path = "codegen/", version = "0.1.0" }
terraform-schema = { path = "schema/", version = "0.1.0" }
semver = "1.0.16"
