[package]
name = "terraform-bindgen"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
	"core",
	"schema"
]
exclude = [
	"examples/kubernetes"
]

[dependencies]
heck = "0.4.1"
nom = "7.1.3"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
thiserror = "1.0.38"
toml = "0.7.2"
terraform-schema = { path = "schema/", version = "0.1.0" }
