[package]
name = "tf-codegen"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.14.4"
heck = "0.4.1"
quote = "1.0.26"
syn = { version = "1.0.91", features = ["derive", "full"] }
