[book]
authors = ["Robert Oleynik"]
language = "en"
multilingual = false
src = "src"
title = "tf-bindgen"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/robert-oleynik/tf-bindgen"
git-repository-icon = "fa-github"
site-url = "/tf-bindgen/"

[output.html.playground]
runnable = false
