[package]
name = "kubernetes"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tf-bindgen = { path = "../../", version = "0.1.0" }

[dependencies]
tf-bindgen = { version = "0.1.0", path = "../../" }
